### ISSUE TITLE
Assalamualaikum

### ISSUE THREAD

**Issue by cloner3000** [ndunks/qcdesa#1]
petunjuk instalasinya gimana ya mas? terimakasih

**Comment by ndunks** [comment]
blm sempet bikin yang full guide mas. sebenernya si simpel, yg penting nodejs dan npm/yarn udah ada dan accessible via terminal/cmd/powershell..

Sedikit contoh utk Instalasinya ada di file `README.md di sub folder `client` dan `server` di bagian contoh file `deploy.sh`. sementara hanya contoh konfigurasi utk server nginx (file `nginx.conf`). untuk apinya tinggal jalanin file .js aja `node index.js`.

ini untuk menjalan di lokal (development) menggunakan VSCode:
* Buka project (client & server) or open workspace
* Terminal -> Run Task -> serve (server)  utk menjalankan server side
* Terminal -> Run Task -> serve (client) utk menjalankan FrontEnd Web App
* Buka browser http://localhost:8080

**Comment by ndunks** [comment]
Silahkan mas ini udah saya buatkan versi portable https://github.com/ndunks/qcdesa/releases
