### ISSUE TITLE
Not Connect

### ISSUE THREAD

**Issue by bembenk18** [ndunks/qcdesa#7]
Halo mas, kenapa pas diakses dari komputer lain not connect ya? saya coba install di vps juga sama tapi pas di lokal lancar
![image](https://user-images.githubusercontent.com/65327648/184847609-e7fb47cf-86c7-4485-9b99-df47c5ac792c.png)

**Comment by ndunks** [comment]
IP addressnya mas coba di cek

**Comment by bembenk18** [comment]
Solved mas, ternyata harus ubah localhost di file app.563a8c92.js diubah ke ip/domain vps
![image](https://user-images.githubusercontent.com/65327648/185282301-b769b8bc-e981-45cf-9e18-665ed51ab118.png)

**Comment by ndunks** [comment]
nah itu alamat localhost diganti IP publiknya vps, atau IP lokal kalo itu di lokal yang satu jaringan mas.. coba konsul ke temen yg paham networking mas, susah soalnya kalo ndak bisa cek langsung IP nya

**Comment by bembenk18** [comment]
Sudah solved mas terimakasih
