### ISSUE TITLE
Refresh Time

### ISSUE THREAD

**Issue by bembenk18** [ndunks/qcdesa#8]
Untuk mengganti refresh time di result itu dimana ya mas? terimakasih

**Comment by ndunks** [comment]
frontend ya? ada di VueJSnya mas:

**Line 356**

https://github.com/ndunks/qcdesa-client-pwa/blob/4f5845e1d309c8d57121cce9d5430bbb3bba2a47/src/views/Result.vue#L356

**Comment by bembenk18** [comment]
siap terimakasih mas
